run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    min-confidence: 0
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: unexported-return
        severity: warning
        disabled: false

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

