version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - api
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
    - "api/docs\\.go"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    min-confidence: 0
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: api/docs\.go
      text: "avoid meaningless package names"
      linters:
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0

