// Code generated by MockGen. DO NOT EDIT.
// Source: broadcast_service.go
//
// Generated by this command:
//
//	mockgen -source=broadcast_service.go -destination=../mocks/broadcast_service_mock.go -package=mocks BroadcastService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "real-time-leaderboard/internal/module/leaderboard/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroadcastService is a mock of BroadcastService interface.
type MockBroadcastService struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcastServiceMockRecorder
	isgomock struct{}
}

// MockBroadcastServiceMockRecorder is the mock recorder for MockBroadcastService.
type MockBroadcastServiceMockRecorder struct {
	mock *MockBroadcastService
}

// NewMockBroadcastService creates a new mock instance.
func NewMockBroadcastService(ctrl *gomock.Controller) *MockBroadcastService {
	mock := &MockBroadcastService{ctrl: ctrl}
	mock.recorder = &MockBroadcastServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcastService) EXPECT() *MockBroadcastServiceMockRecorder {
	return m.recorder
}

// BroadcastLeaderboard mocks base method.
func (m *MockBroadcastService) BroadcastLeaderboard(ctx context.Context, leaderboard *domain.Leaderboard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastLeaderboard", ctx, leaderboard)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastLeaderboard indicates an expected call of BroadcastLeaderboard.
func (mr *MockBroadcastServiceMockRecorder) BroadcastLeaderboard(ctx, leaderboard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastLeaderboard", reflect.TypeOf((*MockBroadcastService)(nil).BroadcastLeaderboard), ctx, leaderboard)
}

// PublishScoreUpdate mocks base method.
func (m *MockBroadcastService) PublishScoreUpdate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishScoreUpdate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishScoreUpdate indicates an expected call of PublishScoreUpdate.
func (mr *MockBroadcastServiceMockRecorder) PublishScoreUpdate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishScoreUpdate", reflect.TypeOf((*MockBroadcastService)(nil).PublishScoreUpdate), ctx)
}

// SubscribeToLeaderboardUpdates mocks base method.
func (m *MockBroadcastService) SubscribeToLeaderboardUpdates(ctx context.Context) (<-chan *domain.Leaderboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToLeaderboardUpdates", ctx)
	ret0, _ := ret[0].(<-chan *domain.Leaderboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToLeaderboardUpdates indicates an expected call of SubscribeToLeaderboardUpdates.
func (mr *MockBroadcastServiceMockRecorder) SubscribeToLeaderboardUpdates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToLeaderboardUpdates", reflect.TypeOf((*MockBroadcastService)(nil).SubscribeToLeaderboardUpdates), ctx)
}

// SubscribeToScoreUpdates mocks base method.
func (m *MockBroadcastService) SubscribeToScoreUpdates(ctx context.Context) (<-chan struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToScoreUpdates", ctx)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToScoreUpdates indicates an expected call of SubscribeToScoreUpdates.
func (mr *MockBroadcastServiceMockRecorder) SubscribeToScoreUpdates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToScoreUpdates", reflect.TypeOf((*MockBroadcastService)(nil).SubscribeToScoreUpdates), ctx)
}
