// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../mocks/repository_mock.go -package=mocks UserRepository,LeaderboardBackupRepository,LeaderboardRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "real-time-leaderboard/internal/module/leaderboard/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByIDs mocks base method.
func (m *MockUserRepository) GetByIDs(ctx context.Context, userIDs []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockUserRepositoryMockRecorder) GetByIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockUserRepository)(nil).GetByIDs), ctx, userIDs)
}

// MockLeaderboardBackupRepository is a mock of LeaderboardBackupRepository interface.
type MockLeaderboardBackupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardBackupRepositoryMockRecorder
	isgomock struct{}
}

// MockLeaderboardBackupRepositoryMockRecorder is the mock recorder for MockLeaderboardBackupRepository.
type MockLeaderboardBackupRepositoryMockRecorder struct {
	mock *MockLeaderboardBackupRepository
}

// NewMockLeaderboardBackupRepository creates a new mock instance.
func NewMockLeaderboardBackupRepository(ctrl *gomock.Controller) *MockLeaderboardBackupRepository {
	mock := &MockLeaderboardBackupRepository{ctrl: ctrl}
	mock.recorder = &MockLeaderboardBackupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardBackupRepository) EXPECT() *MockLeaderboardBackupRepositoryMockRecorder {
	return m.recorder
}

// GetLeaderboard mocks base method.
func (m *MockLeaderboardBackupRepository) GetLeaderboard(ctx context.Context) (*domain.Leaderboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboard", ctx)
	ret0, _ := ret[0].(*domain.Leaderboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderboard indicates an expected call of GetLeaderboard.
func (mr *MockLeaderboardBackupRepositoryMockRecorder) GetLeaderboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboard", reflect.TypeOf((*MockLeaderboardBackupRepository)(nil).GetLeaderboard), ctx)
}

// UpsertScore mocks base method.
func (m *MockLeaderboardBackupRepository) UpsertScore(ctx context.Context, userID string, score int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScore", ctx, userID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScore indicates an expected call of UpsertScore.
func (mr *MockLeaderboardBackupRepositoryMockRecorder) UpsertScore(ctx, userID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScore", reflect.TypeOf((*MockLeaderboardBackupRepository)(nil).UpsertScore), ctx, userID, score)
}

// MockLeaderboardRepository is a mock of LeaderboardRepository interface.
type MockLeaderboardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardRepositoryMockRecorder
	isgomock struct{}
}

// MockLeaderboardRepositoryMockRecorder is the mock recorder for MockLeaderboardRepository.
type MockLeaderboardRepositoryMockRecorder struct {
	mock *MockLeaderboardRepository
}

// NewMockLeaderboardRepository creates a new mock instance.
func NewMockLeaderboardRepository(ctrl *gomock.Controller) *MockLeaderboardRepository {
	mock := &MockLeaderboardRepository{ctrl: ctrl}
	mock.recorder = &MockLeaderboardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardRepository) EXPECT() *MockLeaderboardRepositoryMockRecorder {
	return m.recorder
}

// GetTopPlayers mocks base method.
func (m *MockLeaderboardRepository) GetTopPlayers(ctx context.Context, limit, offset int64) ([]domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopPlayers", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopPlayers indicates an expected call of GetTopPlayers.
func (mr *MockLeaderboardRepositoryMockRecorder) GetTopPlayers(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPlayers", reflect.TypeOf((*MockLeaderboardRepository)(nil).GetTopPlayers), ctx, limit, offset)
}

// GetTotalPlayers mocks base method.
func (m *MockLeaderboardRepository) GetTotalPlayers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPlayers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPlayers indicates an expected call of GetTotalPlayers.
func (mr *MockLeaderboardRepositoryMockRecorder) GetTotalPlayers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPlayers", reflect.TypeOf((*MockLeaderboardRepository)(nil).GetTotalPlayers), ctx)
}

// UpdateScore mocks base method.
func (m *MockLeaderboardRepository) UpdateScore(ctx context.Context, userID string, score int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, userID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockLeaderboardRepositoryMockRecorder) UpdateScore(ctx, userID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockLeaderboardRepository)(nil).UpdateScore), ctx, userID, score)
}
