// Code generated by MockGen. DO NOT EDIT.
// Source: real-time-leaderboard/internal/module/leaderboard/application (interfaces: BroadcastService)
//
// Generated by this command:
//
//	mockgen -destination=../infrastructure/mocks/broadcast_service_mock.go -package=mocks real-time-leaderboard/internal/module/leaderboard/application BroadcastService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "real-time-leaderboard/internal/module/leaderboard/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroadcastService is a mock of BroadcastService interface.
type MockBroadcastService struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcastServiceMockRecorder
	isgomock struct{}
}

// MockBroadcastServiceMockRecorder is the mock recorder for MockBroadcastService.
type MockBroadcastServiceMockRecorder struct {
	mock *MockBroadcastService
}

// NewMockBroadcastService creates a new mock instance.
func NewMockBroadcastService(ctrl *gomock.Controller) *MockBroadcastService {
	mock := &MockBroadcastService{ctrl: ctrl}
	mock.recorder = &MockBroadcastServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcastService) EXPECT() *MockBroadcastServiceMockRecorder {
	return m.recorder
}

// BroadcastEntryUpdate mocks base method.
func (m *MockBroadcastService) BroadcastEntryUpdate(ctx context.Context, entry *domain.LeaderboardEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastEntryUpdate", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// BroadcastEntryUpdate indicates an expected call of BroadcastEntryUpdate.
func (mr *MockBroadcastServiceMockRecorder) BroadcastEntryUpdate(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastEntryUpdate", reflect.TypeOf((*MockBroadcastService)(nil).BroadcastEntryUpdate), ctx, entry)
}

// SubscribeToEntryUpdates mocks base method.
func (m *MockBroadcastService) SubscribeToEntryUpdates(ctx context.Context) (<-chan *domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToEntryUpdates", ctx)
	ret0, _ := ret[0].(<-chan *domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToEntryUpdates indicates an expected call of SubscribeToEntryUpdates.
func (mr *MockBroadcastServiceMockRecorder) SubscribeToEntryUpdates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToEntryUpdates", reflect.TypeOf((*MockBroadcastService)(nil).SubscribeToEntryUpdates), ctx)
}
