// Code generated by MockGen. DO NOT EDIT.
// Source: real-time-leaderboard/internal/module/leaderboard/application (interfaces: UserRepository,LeaderboardPersistenceRepository,LeaderboardCacheRepository)
//
// Generated by this command:
//
//	mockgen -destination=../infrastructure/mocks/repository_mock.go -package=mocks real-time-leaderboard/internal/module/leaderboard/application UserRepository,LeaderboardPersistenceRepository,LeaderboardCacheRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "real-time-leaderboard/internal/module/leaderboard/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByIDs mocks base method.
func (m *MockUserRepository) GetByIDs(ctx context.Context, userIDs []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, userIDs)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockUserRepositoryMockRecorder) GetByIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockUserRepository)(nil).GetByIDs), ctx, userIDs)
}

// MockLeaderboardPersistenceRepository is a mock of LeaderboardPersistenceRepository interface.
type MockLeaderboardPersistenceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardPersistenceRepositoryMockRecorder
	isgomock struct{}
}

// MockLeaderboardPersistenceRepositoryMockRecorder is the mock recorder for MockLeaderboardPersistenceRepository.
type MockLeaderboardPersistenceRepositoryMockRecorder struct {
	mock *MockLeaderboardPersistenceRepository
}

// NewMockLeaderboardPersistenceRepository creates a new mock instance.
func NewMockLeaderboardPersistenceRepository(ctrl *gomock.Controller) *MockLeaderboardPersistenceRepository {
	mock := &MockLeaderboardPersistenceRepository{ctrl: ctrl}
	mock.recorder = &MockLeaderboardPersistenceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardPersistenceRepository) EXPECT() *MockLeaderboardPersistenceRepositoryMockRecorder {
	return m.recorder
}

// GetLeaderboard mocks base method.
func (m *MockLeaderboardPersistenceRepository) GetLeaderboard(ctx context.Context) ([]domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboard", ctx)
	ret0, _ := ret[0].([]domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderboard indicates an expected call of GetLeaderboard.
func (mr *MockLeaderboardPersistenceRepositoryMockRecorder) GetLeaderboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboard", reflect.TypeOf((*MockLeaderboardPersistenceRepository)(nil).GetLeaderboard), ctx)
}

// UpsertScore mocks base method.
func (m *MockLeaderboardPersistenceRepository) UpsertScore(ctx context.Context, userID string, score int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertScore", ctx, userID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertScore indicates an expected call of UpsertScore.
func (mr *MockLeaderboardPersistenceRepositoryMockRecorder) UpsertScore(ctx, userID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertScore", reflect.TypeOf((*MockLeaderboardPersistenceRepository)(nil).UpsertScore), ctx, userID, score)
}

// MockLeaderboardCacheRepository is a mock of LeaderboardCacheRepository interface.
type MockLeaderboardCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockLeaderboardCacheRepositoryMockRecorder is the mock recorder for MockLeaderboardCacheRepository.
type MockLeaderboardCacheRepositoryMockRecorder struct {
	mock *MockLeaderboardCacheRepository
}

// NewMockLeaderboardCacheRepository creates a new mock instance.
func NewMockLeaderboardCacheRepository(ctrl *gomock.Controller) *MockLeaderboardCacheRepository {
	mock := &MockLeaderboardCacheRepository{ctrl: ctrl}
	mock.recorder = &MockLeaderboardCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboardCacheRepository) EXPECT() *MockLeaderboardCacheRepositoryMockRecorder {
	return m.recorder
}

// GetTopPlayers mocks base method.
func (m *MockLeaderboardCacheRepository) GetTopPlayers(ctx context.Context, limit, offset int64) ([]domain.LeaderboardEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopPlayers", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.LeaderboardEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopPlayers indicates an expected call of GetTopPlayers.
func (mr *MockLeaderboardCacheRepositoryMockRecorder) GetTopPlayers(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPlayers", reflect.TypeOf((*MockLeaderboardCacheRepository)(nil).GetTopPlayers), ctx, limit, offset)
}

// GetTotalPlayers mocks base method.
func (m *MockLeaderboardCacheRepository) GetTotalPlayers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPlayers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPlayers indicates an expected call of GetTotalPlayers.
func (mr *MockLeaderboardCacheRepositoryMockRecorder) GetTotalPlayers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPlayers", reflect.TypeOf((*MockLeaderboardCacheRepository)(nil).GetTotalPlayers), ctx)
}

// GetUserRank mocks base method.
func (m *MockLeaderboardCacheRepository) GetUserRank(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRank", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRank indicates an expected call of GetUserRank.
func (mr *MockLeaderboardCacheRepositoryMockRecorder) GetUserRank(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRank", reflect.TypeOf((*MockLeaderboardCacheRepository)(nil).GetUserRank), ctx, userID)
}

// UpdateScore mocks base method.
func (m *MockLeaderboardCacheRepository) UpdateScore(ctx context.Context, userID string, score int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, userID, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockLeaderboardCacheRepositoryMockRecorder) UpdateScore(ctx, userID, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockLeaderboardCacheRepository)(nil).UpdateScore), ctx, userID, score)
}
