// Code generated by MockGen. DO NOT EDIT.
// Source: real-time-leaderboard/internal/module/leaderboard/application (interfaces: ScoreUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../adapters/mocks/score_usecase_mock.go -package=mocks real-time-leaderboard/internal/module/leaderboard/application ScoreUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	application "real-time-leaderboard/internal/module/leaderboard/application"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockScoreUseCase is a mock of ScoreUseCase interface.
type MockScoreUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockScoreUseCaseMockRecorder
	isgomock struct{}
}

// MockScoreUseCaseMockRecorder is the mock recorder for MockScoreUseCase.
type MockScoreUseCaseMockRecorder struct {
	mock *MockScoreUseCase
}

// NewMockScoreUseCase creates a new mock instance.
func NewMockScoreUseCase(ctrl *gomock.Controller) *MockScoreUseCase {
	mock := &MockScoreUseCase{ctrl: ctrl}
	mock.recorder = &MockScoreUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoreUseCase) EXPECT() *MockScoreUseCaseMockRecorder {
	return m.recorder
}

// SubmitScore mocks base method.
func (m *MockScoreUseCase) SubmitScore(ctx context.Context, userID string, req application.SubmitScoreRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitScore", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitScore indicates an expected call of SubmitScore.
func (mr *MockScoreUseCaseMockRecorder) SubmitScore(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitScore", reflect.TypeOf((*MockScoreUseCase)(nil).SubmitScore), ctx, userID, req)
}
